import type { Metadata } from 'next'
import { ClerkProvider, SignedIn, UserButton } from '@clerk/nextjs'
import { Geist, Geist_Mono } from 'next/font/google'
import './globals.css'
import { dark } from '@clerk/themes'

const geistSans = Geist({
  variable: '--font-geist-sans',
  subsets: ['latin'],
})

const geistMono = Geist_Mono({
  variable: '--font-geist-mono',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: 'Clerk Next.js Quickstart',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark
      }}>
      <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-black`}>
          {/* <header className="flex justify-end items-center p-4 gap-4 h-16"> */}
          {/* <SignedOut>
              <SignInButton />
              <SignUpButton />
            </SignedOut> */}
          <SignedIn>
            <header className="flex justify-end items-center p-4 gap-4 h-16">
              <UserButton
                appearance={{
                  elements: {
                    userButtonPopoverFooter: {
                      display: 'none'
                    }
                  }
                }}
              />
            </header>
          </SignedIn>
          {/* </header> */}
          {children}
        </body>
      </html>
    </ClerkProvider>
  )
}